### ISSUE TITLE
✨ feat:릴스 - 리덕스 활용하여 로컬 상태 관리

### ISSUE THREAD

**Issue by happygirlll** [PrograMemo-Groom/instagram-clone#57]
### **Problem**
- 인스타 api에 노래 제공 안함
- 인스타 api에 댓글 연결할 시, 앱 배포 해야함
- 시간 관계상 파이어베이스 연결 못함

### **Solution**
리덕스로 데이터 관리하여 ui로 나타내기
<br>

### **Task**

> **릴스 메인**

- [x] 릴스 `무한 스크롤` 구현
- [x] 릴스 마우스 아래로 스크롤 한번 할 시, 다음 릴스로 연결
- [x] 마우스 스크롤 시 하나의 릴스 컴포넌트만 보이게
- [x] `좋아요` 버튼 누를 시, 숫자 증가 및 감소
- [x] 릴스 `노래` UI 부분 대체를 위해, 릴스 `게시 날짜` 추가
- [x] `미디어쿼리` 수정
- [x] 사이드메뉴에 노래 이미지 바꾸기
- [x] 사이드메뉴에 `노래버튼` 클릭하면 `음소거` 가능
- [x] 현재 릴스영상에서 다른 릴스영상 이동시, `이전 릴스 영상 초기화` 및 `재생 중지`
- [x] 릴스 영상 화면 클릭시, `일시정지` 및 `다시 재생`

<br>

> **댓글**

- [x] 댓글 입력창에 댓글 입력 후, 엔터 누르면 `댓글 추가`됨
- [x] 댓글 `사용자 프로필`, `닉네임`, `작성 날짜` 연결
- [x] `좋아요` 버튼 누를 시, 증가 및 감소
